/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RegistrationInput { 'name' : string, 'phoneNumber' : string }
export type Time = bigint;
export interface Transfer {
  'receiverAppID' : bigint,
  'senderAppID' : bigint,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface User {
  'principal' : Principal,
  'balance' : bigint,
  'appID' : bigint,
  'name' : string,
  'phoneNumber' : string,
}
export interface UserProfile {
  'appID' : bigint,
  'name' : string,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getBalance' : ActorMethod<[bigint], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTransactionHistory' : ActorMethod<[bigint], Array<Transfer>>,
  'getUser' : ActorMethod<[bigint], User>,
  'getUserByPhone' : ActorMethod<[string], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[RegistrationInput], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transfer' : ActorMethod<[Transfer], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];