/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appID' : IDL.Nat,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const Time = IDL.Int;
export const Transfer = IDL.Record({
  'receiverAppID' : IDL.Nat,
  'senderAppID' : IDL.Nat,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const User = IDL.Record({
  'principal' : IDL.Principal,
  'balance' : IDL.Nat,
  'appID' : IDL.Nat,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const RegistrationInput = IDL.Record({
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBalance' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTransactionHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Transfer)], ['query']),
  'getUser' : IDL.Func([IDL.Nat], [User], ['query']),
  'getUserByPhone' : IDL.Func([IDL.Text], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([RegistrationInput], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transfer' : IDL.Func([Transfer], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'appID' : IDL.Nat,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const Time = IDL.Int;
  const Transfer = IDL.Record({
    'receiverAppID' : IDL.Nat,
    'senderAppID' : IDL.Nat,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const User = IDL.Record({
    'principal' : IDL.Principal,
    'balance' : IDL.Nat,
    'appID' : IDL.Nat,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const RegistrationInput = IDL.Record({
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBalance' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTransactionHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transfer)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Nat], [User], ['query']),
    'getUserByPhone' : IDL.Func([IDL.Text], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([RegistrationInput], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transfer' : IDL.Func([Transfer], [], []),
  });
};

export const init = ({ IDL }) => { return []; };